### ISSUE TITLE
Update documentation to eliminate confusion

### ISSUE THREAD

**Issue by c0deright** [dashpay/insight-api#29]
Hi,

the documentation in https://github.com/dashevo/insight-api/tree/master#getting-started is wrong:

* replace `bitcore-node-dash` with `dashcore-node`
* replace `dashcore-node install insight-api` with `dashcore-node install @dashevo/insight-api`

This all adds to many confusions (https://github.com/dashevo/dashcore-node/issues/33)

**Comment by Cofresi** [comment]
Fixed with #33
