### ISSUE TITLE
Doc: Endpoint /insight-api-dash is wrong

### ISSUE THREAD

**Issue by c0deright** [dashpay/insight-api#31]
Documentation says endpoint is `/insight-api-dash` but that's wrong. Endpoint is `/insight-api`

**Comment by Cofresi** [comment]
Thanks! /insight-api-dash was the old naming from when we first forked it which was later changed but never adjusted in the README. Should be fixed with #36

**Comment by nmarley** [comment]
This should be fixed now. Thanks for reporting!
