### ISSUE TITLE
Cannot get balance, using library.

### ISSUE THREAD

**Issue by sollerias** [dashpay/insight-api#68]
Hi, devs!

I've been trying to solve a problem with a balance request from a test node via a `https://github.com/dashevo/insight-api` library for several days. Together with the guys from the discord channel 'https://discord.gg/wq5suh' (Dash Devs), I came to the following conclusions:
1. Testnet node receives data from the blockchain 1 second after it appears in the explorer (like so: https://blockexplorer.one/dash/testnet)
2. Testnet node receives the right amount of address balance.
3. `https://github.com/dashevo/insight-api` library can't provide balance info after the balance change. The library doesn't update address balance.

My flow is so:
1. docker container with `https://github.com/dashevo/insight-api` image
2. remote testnet node
3. my project, which make requests to `https://github.com/dashevo/insight-api` docker container.

What I do:
1. run `https://github.com/dashevo/insight-api` docker container using `docker run --rm --net="host" -p 3001:3001 dash-insight:v1` command
2. execute getBalance command from my project code: `axios.get(http://localhost:3001/insight-api/addr/ygsU7azZDDPCKtPoNd7gnNZDiXTPdzwLaX/balance)`
3. The step above is correctly executed only once per `https://github.com/dashevo/insight-api` docker container session (until docker container reload). The first time, the command from step 2 will initiate these commands on the testnet node:
```
	2020-10-13 13:16:16 Received a POST request for / from 78.81.164.236:46700
	2020-10-13 13:16:16 ThreadRPCServer method=getaddressbalance
	2020-10-13 13:16:16 Received a POST request for / from 78.81.164.236:46698
	2020-10-13 13:16:16 ThreadRPCServer method=getaddresstxids
	2020-10-13 13:16:16 Received a POST request for / from 78.81.164.236:46702
	2020-10-13 13:16:16 ThreadRPCServer method=getaddressmempool
```
4. In all other cases, step 2 runs only these commands in the testnet node:
```
2020-10-13 13:24:10 Received a POST request for / from 78.81.164.236:46888
2020-10-13 13:24:10 ThreadRPCServer method=getaddressmempool
```

The "method = getaddressbalance" request is missing.
My question is: why is this so? What is the problem and how can I solve it? Maybe it's something in `https://github.com/dashevo/insight-api` config and I need to change that?

**Comment by sollerias** [comment]
My `dashcore-node.json` file:
```
{
  "network": "testnet",
  "port": 3001,
  "services": [
    "dashd",
    "web",
    "@dashevo/insight-api"
  ],
  "servicesConfig": {
    "insight-api": {
      "disableRateLimiter": true
    },
    "dashd": {
      "connect": [{
        "rpchost": "12.345.67.89",
        "rpcport": 19998,
        "rpcuser": "user",
        "rpcpassword": "pass",
        "zmqpubrawtx": "tcp://12.345.67.89:29998",
        "zmqpubhashblock": "tcp://12.345.67.89:29998"
      }]
    }
  }
}
```

**Comment by sollerias** [comment]
@shumkov , @antouhou , @shuplenkov. 

Hi, guys! Are there any updates on my issue? Maybe some small advice to help me break the chains of misunderstanding? It's the fourth day when I'm struggling with this situation. Thought it might be the wrong docker startup command. So I changed the command from this: `docker run --rm --net =" host "-p 3001: 3001 dash-insight: v1` to this:` docker run --rm -p 3001: 3001 dash-insight: v1 `, but nothing has changed.

**Comment by antouhou** [comment]
Hey @sollerias! It's probably something to do with the Insight cache. Currently, the whole team is busy with rolling out platform 0.16 to the evonet, but we'll look into the issue afterwards - probablt next week. Thank you!

**Comment by sollerias** [comment]
@antouhou, thanks for the advice! I just started logging methods for getting the balance and caching data in the `dashevo/insight-api` library.

**Comment by sollerias** [comment]
Unfortunately, I couldn't solve the problem, so I took another library.
