### ISSUE TITLE
Transaction broadcast failed

### ISSUE THREAD

**Issue by ghost** [dashpay/insight-api#85]
I have send transaction signed (with rawtx) but get error `Second argument must be numeric (maxfeerate) and no longer supports a boolean. To allow a transaction with high fees, set maxfeerate to 0.. Code:-8`.
Please let me know if isight-api have any updates!

**Comment by ghost** [comment]
@antouhou Hi. Any updated for libs ?

**Comment by vvpgrp** [comment]
**I have the same error!**

**Comment by shumkov** [comment]
Fixed with #86 in v3.2.0
